version: 1
runtime: custom
vm: true
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: server.dart
  login: required

health_check:
  enable_health_check: False
  check_interval_sec: 1
  timeout_sec: 1

manual_scaling:
  instances: 1
